version: '2'

services:
  db:
    image: mysql:5.5
    container_name: mysql_wordpress
    networks:
      - net-backend
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:4.7-php5.6
    container_name: web_wordpres
    networks:
      - net-backend
    ports: 
      - '9090:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

networks:
  net-backend:

volumes:
  db_data: